GET  http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MjlkYzNlOWE0MzU2NWQzZTQ0MjA0MzkiLCJpYXQiOjE2NTQ1MDcyMjR9.CM1tEYft2OCoWNRRv1t9YvZ-RqomY1RE9h9bryqyFnw

{
    "title": "React patterns3",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 5
}

###
GET  http://localhost:3003/api/blogs/629dcb878eb6174b985a699d

###
PUT  http://localhost:3003/api/blogs/629cf624f9117f15b3aedafb
content-type: application/json

{
    "title": "React patterns",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 300
}

###
DELETE   http://localhost:3003/api/blogs/629dcb878eb6174b985a699d
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MjlkYzNlOWE0MzU2NWQzZTQ0MjA0MzkiLCJpYXQiOjE2NTQ1MDcyMjR9.CM1tEYft2OCoWNRRv1t9YvZ-RqomY1RE9h9bryqyFnw