GET  http://localhost:3003/api/users
###
POST http://localhost:3003/api/users
content-type: application/json

{
    "name": "React learner",
    "username": "Michael Chan",
    "password": "https://reactpatterns.com/"
}